version: '3'
services:
 nginx:
  image: nginx
  restart: always
  build: requirements/nginx
  container_name: nginx
  ports:
   - "443:443"
  extra_hosts:
    - "sthrace.42.fr:127.0.0.1"
  env_file: .env