version: '3'
services:
  wordpress:
    image: wordpress
    build: requirements/wordpress
    container_name: wordpress
    restart: unless-stopped
    networks:
      - incept-network
    env_file: .env
    volumes:
      - wp:/var/www/wordpress
    depends_on: 
      - mysql
  nginx:
    image: nginx
    build: requirements/nginx
    container_name: nginx
    restart: unless-stopped
    ports:
    - "443:443"
    networks:
      - incept-network
    volumes:
      - wp:/var/www/wordpress
    depends_on: 
      - wordpress
  mysql:
    image: mysql
    build: 
      context: requirements/mariadb/
      # args:
      #   DB_NAME=$MYSQL_DB
      #   DB_USER=$MYSQL_USER
      #   DB_PASS=$MYSQL_PASSWORD
      #   RT_PASS=$MYSQL_ROOT_PASSWORD
    container_name: mysql
    restart: unless-stopped
    networks:
      - incept-network
    volumes:
      - db:/var/lib/mysql
    env_file: .env
networks:
  incept-network:
volumes:
  wp:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/sthrace/data/wp
  db:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/sthrace/data/db