version: '3'
services:
  wordpress:
    image: wordpress
    build: requirements/wordpress
    container_name: wordpress
    restart: unless-stopped
    networks:
      - incept-network
    env_file: .env
    volumes:
      - wp:/var/www/html/wordpress
  nginx:
    image: nginx
    build: requirements/nginx
    container_name: nginx
    restart: unless-stopped
    ports:
    - "443:443"
    networks:
      - incept-network
networks:
  incept-network:
    driver: bridge
volumes:
  wp:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /Users/sthrace/data/wordpress